from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Base paths
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)

DB_PATH = DATA_DIR / "bot.db"

# Environment / API
BRAIN_USERNAME = os.getenv("BRAIN_USERNAME", "")
BRAIN_PASSWORD = os.getenv("BRAIN_PASSWORD", "")

# Scheduler / runtime
MAX_CONCURRENT_SIMS = 3
POLL_INTERVAL_SECONDS = 20
SESSION_REFRESH_MINUTES = 150
SIM_TIMEOUT_MINUTES = 45

# Default simulation settings
DEFAULT_REGION = "USA"
DEFAULT_DELAY = 1
DEFAULT_DELAYS = [1]
DEFAULT_UNIVERSES = ["TOP3000", "TOP1000", "TOP500", "TOP200", "TOPSP500"]
DEFAULT_NEUTRALIZATIONS = ["NONE", "MARKET", "SECTOR", "INDUSTRY", "SUBINDUSTRY"]
DEFAULT_DECAYS = [2, 4, 6, 8, 10]
DEFAULT_TRUNCATIONS = [0.05, 0.08, 0.10]

DEFAULT_INSTRUMENT_TYPE = "EQUITY"
DEFAULT_VISUALIZATION = False

DEFAULT_PASTEURIZATION = "ON"
DEFAULT_UNIT_HANDLING = "VERIFY"
DEFAULT_NAN_HANDLING = "OFF"
DEFAULT_MAX_STOCK_WEIGHT = 0.10
DEFAULT_LANGUAGE = "FASTEXPR"

# Evaluation thresholds
MIN_SHARPE = 1.25
MIN_FITNESS = 1.00
MAX_TURNOVER = 0.70

# Near-passer / refinement settings
NEAR_PASSER_MIN_SHARPE = 1.55
NEAR_PASSER_MIN_FITNESS = 0.82
NEAR_PASSER_MAX_TURNOVER = 0.72
REFINEMENT_PROBABILITY = 0.45

MIN_REFINEMENT_SHARPE = 1.20
LOW_FITNESS_REFINEMENT_PRIORITY_BONUS = 0.18
HIGH_TURNOVER_REFINEMENT_PRIORITY_BONUS = 0.12

# Refinement / local search behaviour
REFINEMENT_TEMPLATE_SWITCH_PROB = 0.20
REFINEMENT_SMOOTHING_WINDOWS = [3, 5, 10]
REFINEMENT_FORCE_SMOOTH_PROB = 0.80
REFINEMENT_RAW_RANK_PROB = 0.03

# Settings-aware refinement controls
REFINEMENT_DECAYS = [4, 6, 8, 10]
REFINEMENT_UNIVERSES = ["TOP3000", "TOP1000", "TOP500", "TOP200", "TOPSP500"]
REFINEMENT_TRUNCATIONS = [0.05, 0.08, 0.10]
REFINEMENT_UNIVERSE_SWITCH_PROB = 0.28
REFINEMENT_DELAY_SWITCH_PROB = 0.0
REFINEMENT_NAN_EXPERIMENT_PROB = 0.02
REFINEMENT_PASTEURIZATION_EXPERIMENT_PROB = 0.01

# Expression-shape controls
FRESH_FORCE_SMOOTH_PROB = 0.55
FRESH_RAW_RANK_PROB = 0.06
LOW_SHARPE_EXTRA_SIGNAL_PROB = 0.50
LOW_FITNESS_STAY_IN_TEMPLATE_PROB = 0.80
HIGH_TURNOVER_STAY_IN_TEMPLATE_PROB = 0.90

# Hard blocks / penalties for empirically bad paths
DISABLED_REFINEMENT_TEMPLATES = {"vol_02"}
TINY_EXPLORATION_TEMPLATES = {"cond_03"}
TINY_EXPLORATION_PROB = 0.03

# Diversity / anti-self-correlation
DIVERSITY_LOOKBACK_RUNS = 120
MAX_RECENT_TEMPLATE_COUNT = 16
RELAXED_TEMPLATE_COUNT = 8
RELAXED_TEMPLATE_MIN_AVG_SHARPE = 1.45
RELAXED_TEMPLATE_MIN_AVG_FITNESS = 0.80
DIVERSITY_EXPLORATION_PROBABILITY = 0.08
MAX_REFINEMENT_ATTEMPTS_PER_BASE = 6

# Template scoring / pruning
TEMPLATE_SCORE_LOOKBACK_RUNS = 180
MIN_TEMPLATE_OBS_FOR_PRUNE = 6

HARD_PRUNE_MAX_AVG_SHARPE = 0.20
HARD_PRUNE_MAX_AVG_FITNESS = 0.10

SOFT_PRUNE_MAX_AVG_SHARPE = 0.60
SOFT_PRUNE_MAX_AVG_FITNESS = 0.35

TEMPLATE_EXPLORATION_PROBABILITY = 0.10
SOFT_PRUNE_REFINEMENT_PROBABILITY = 0.35

DEFAULT_FAMILY_ORDER = [
    "mean_reversion",
    "conditional",
    "volume_flow",
    "vol_adjusted",
    "fundamental",
    "momentum",
]

PREFERRED_TEMPLATE_BOOSTS = {
    "mr_04": 1.22,
    "va_02": 1.32,
    "vol_03": 1.28,
    "mr_01": 1.10,
    "cond_01": 1.06,
}

TEMPLATE_WEIGHT_PENALTIES = {
    "va_01": 0.18,
    "vol_01": 0.55,
    "vol_02": 0.02,
    "cond_02": 0.70,
    "cond_03": 0.04,
    "fund_01": 0.50,
    "fund_02": 0.50,
    "fund_03": 0.50,
    "mom_01": 0.05,
    "mom_02": 0.05,
    "mom_03": 0.05,
}

# =========================================================
# Phase 2: structural similarity / portfolio-awareness
# =========================================================
SIMILARITY_REFERENCE_LOOKBACK = 120
SIMILARITY_MIN_REF_SHARPE = 1.25
SIMILARITY_MIN_REF_FITNESS = 0.75
SIMILARITY_MIN_REFERENCE_COUNT = 12

MAX_FRESH_CANDIDATE_SIMILARITY = 0.94
MAX_REFINEMENT_CANDIDATE_SIMILARITY = 0.97

FAMILY_FRESH_SIMILARITY_THRESHOLDS = {
    "mean_reversion": 0.95,
    "conditional": 0.95,
    "volume_flow": 0.93,
    "vol_adjusted": 0.94,
    "momentum": 0.92,
    "fundamental": 0.91,
}

FAMILY_REFINEMENT_SIMILARITY_THRESHOLDS = {
    "mean_reversion": 0.98,
    "conditional": 0.98,
    "volume_flow": 0.96,
    "vol_adjusted": 0.97,
    "momentum": 0.95,
    "fundamental": 0.94,
}

SIMILARITY_SOFT_MARGIN = 0.020
SIMILARITY_SOFT_ALLOW_PROB_FRESH = 0.30
SIMILARITY_SOFT_ALLOW_PROB_REFINEMENT = 0.55
SIMILARITY_SAME_BUCKET_PENALTY = 0.10

BUCKET_REFERENCE_LOOKBACK = 180
MAX_BUCKET_OCCUPANCY = 18
MAX_STRONG_BUCKET_OCCUPANCY = 8
STRONG_BUCKET_MIN_SHARPE = 1.55
STRONG_BUCKET_MIN_FITNESS = 0.90

FAMILY_MAX_BUCKET_OCCUPANCY = {
    "mean_reversion": 20,
    "conditional": 18,
    "volume_flow": 14,
    "vol_adjusted": 16,
    "momentum": 12,
    "fundamental": 12,
}

FAMILY_MAX_STRONG_BUCKET_OCCUPANCY = {
    "mean_reversion": 10,
    "conditional": 8,
    "volume_flow": 6,
    "vol_adjusted": 7,
    "momentum": 5,
    "fundamental": 5,
}

BUCKET_SOFT_ALLOW_PROB_FRESH = 0.18
BUCKET_SOFT_ALLOW_PROB_REFINEMENT = 0.40
STRONG_BUCKET_SOFT_ALLOW_PROB_FRESH = 0.02
STRONG_BUCKET_SOFT_ALLOW_PROB_REFINEMENT = 0.10

SUBMISSION_PORTFOLIO_LOOKBACK = 300
SUBMISSION_MAX_SELECTED_PER_CYCLE = 3
SUBMISSION_MAX_PAIRWISE_SIMILARITY = 0.86

# Submission behaviour
AUTO_SUBMIT = False

# Logging / reporting
REPORT_EVERY_N_COMPLETIONS = 25
REPORT_RECENT_FAILURE_LOOKBACK = 180
NEAR_MISS_REPORT_COUNT = 6
